version: '2'
services:
  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "6Xs946IaX1"
    volumes:
      - ./mysql/config/my.cnf:/etc/my.cnf:ro
      - ./mysql/data/:/var/lib/mysql/:rw
      - ./mysql/log/:/var/log/mysql/:rw

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/data:/data/:rw
    command:
      "redis-server /usr/local/etc/redis/redis.conf"

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: 172.17.0.1
      ELASTICSEARCH_URL: http://172.17.0.1:9200
    networks:
      - elk
    depends_on:
      - elasticsearch1
      - elasticsearch2

networks:
  elk:
    driver: bridge

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
